language: python
python:
  - 3.8

stages:
  - lint
  # Only execute deployment stage on tagged release commits in the form of "v1.2.3"
  # and from your repository (e.g. not PRs).
  # Also allows alpha/beta releases such as "v1.2.3b2"
  - name: deploy
    if: repo = SystemRDL/pygments-systemrdl AND tag =~ ^v\d+\.\d+\.\w+$

jobs:
  include:
    - stage: lint
      name: Lint
      install:
        - python -m pip install pylint
        - python -m pip install .
      script: pylint --rcfile .pylint.rc rdl_pygments

    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      install: python -m pip install twine
      script: python setup.py sdist --formats=gztar
      after_success: python -m twine upload --skip-existing dist/*.tar.gz
